CREATE TABLE messages (
email varchar(50) NOT NULL,
phone varchar(15),
subject varchar(200),
message varchar2(4000),
response varchar2(4000),
status int default 0,
posted_date date default sysdate,
created date default sysdate,
created_pk varchar(35) DEFAULT NULL,
created_ip varchar(15) NOT NULL,
updated date default sysdate,
updated_pk varchar(35) DEFAULT NULL,
updated_ip varchar(15) NOT NULL,
);